openapi: 3.0.0
info:
  title: Payment API
  description: API for handling payments using Midtrans and fake payment validation
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: Payments
    description: Payment operations

paths:
  /payments/midtrans/token/{bookingId}:
    post:
      tags:
        - Payments
      summary: Create a payment token using Midtrans
      parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentMethod:
                  type: string
                  example: credit_card
      responses:
        '200':
          description: Token retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: Token retrieved successfully
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: 2304b11f-fd1f-425e-b481-ced5e3f349c6
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid booking ID
                  data:
                    example: ~
        '404':
          description: Booking not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Booking Not Found With Id 100
                  data:
                    example: ~
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Server error during token creation
                  data:
                    example: ~

  /payments/midtrans/confirm:
    post:
      tags:
        - Payments
      summary: Confirm payment using Midtrans
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order_id:
                  type: string
                  example: 'BOOKING-1-123456789'
                transaction_id:
                  type: string
                  example: 'TRANS123'
                transaction_status:
                  type: string
                  example: 'capture'
                gross_amount:
                  type: number
                  example: 100000
                payment_type:
                  type: string
                  example: 'credit_card'
      responses:
        '200':
          description: Payment confirmed and booking status updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: Payment confirmed and booking status updated successfully
                  data:
                    type: object
                    properties:
                      newPaymentId:
                        type: integer
                        example: 1
                      updatedBookingId:
                        type: integer
                        example: 1
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Transaction is not successful. Status: pending"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Server error during payment confirmation
                  data:
                    example: ~

  /payments/payment/{bookingId}:
    post:
      tags:
        - Payments
      summary: Validate payment with credit card 
      parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentMethod:
                  type: string
                  example: credit_card
                cardNumber:
                  type: string
                  example: 4515678901234
                cardHolderName:
                  type: string
                  example: John Doe
                cvv:
                  type: string
                  example: 123
                expiryDate:
                  type: string
                  example: 12/24
      responses:
        '200':
          description: Payment validated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    example: Credit card payment validated successfully
                  data:
                    type: object
                    properties:
                      booking:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          bookingCode:
                            type: string
                            example: "C8D3543BB0"
                          status:
                            type: string
                            example: "PAID"
                          expiredPaid:
                            type: string
                            format: date-time
                            example: "2024-05-28T15:34:29.303Z"
                          totalPrice:
                            type: number
                            example: 11550000
                          flightId:
                            type: integer
                            example: 5
                          userId:
                            type: integer
                            example: 1
                      payment:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: "credit_card"
                          paidAt:
                            type: string
                            format: date-time
                            example: "2024-05-28T14:35:04.298Z"
                          bookingId:
                            type: integer
                            example: 1
        '400':
          description: Invalid Booking ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Invalid booking ID
                  data:
                    example: ~
        '404':
          description: Booking not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Booking not found
                  data:
                    example: ~
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Server error during payment validation
                  data:
                    example: ~